package com.alexrcq.tvpicturesettings.storage

object PreferencesKeys {
    const val IS_AUTO_DARK_MODE_ENABLED = "auto_backlight"
    const val DAY_MODE_TIME = "ab_day_time"
    const val DARK_MODE_TIME = "ab_night_time"
    const val IS_ADDITIONAL_DIMMING_ENABLED = "is_dark_filter_enabled"
    const val DAY_BACKLIGHT = "ab_day_backlight"
    const val NIGHT_BACKLIGHT = "ab_night_backlight"
    const val TAKE_SCREENSHOT = "take_screenshot"
    const val RESET_TO_DEFAULT = "reset_to_default"
    const val SCREEN_FILTER_POWER = "dark_filter_power"
    const val TURN_OFF_DARK_MODE_ON_SCREEN_ON = "is_enable_day_mode_after_screen_on_enabled"
    const val OPEN_PICTURE_SETTINGS = "open_picture_settings"
    const val APP_DESCRIPTION = "app_description"
    const val IS_WHITE_BALANCE_FIXED = "fix_wb_values"
    const val RED_GAIN = "picture_red_gain"
    const val GREEN_GAIN = "picture_green_gain"
    const val BLUE_GAIN = "picture_blue_gain"
    const val IS_SCREEN_FILTER_ENABLED = "dark_filter_enabled"
    const val VIDEO_PREFERENCES = "video_preferences"
    const val DARK_MODE_PREFERENCES = "dark_mode_preferences"
    const val COLOR_TUNER = "color_tuner"
    const val SATURATION_TUNE = "saturation_tune"
    const val HUE_TUNE = "hue_tune"
    const val BRIGHTNESS_TUNE = "brightness_tune"
    const val OFFSET_TUNE = "offset_tune"
    const val SCHEDULED_DARK_MODE = "scheduled_dark_mode"
    const val WHITE_BALANCE = "white_balance"
    const val RESET_VALUES = "reset_values"
    const val TOGGLE_SCREEN_POWER = "toggle_screen_power"
    const val STEP_BY_STEP_DARK_MODE_ENABLED = "step_by_step_dark_mode_enabled"
    const val CURRENT_MODE_NAME = "mode_name"
    const val SHOW_ABOUT_VIDEO_PREFS_RU_LOCALIZATION = "show_about_video_prefs_ru_localization"
}