name: Build & Publish APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build release APK with debug signature
        run: ./gradlew assembleRelease
        env:
          DEBUG_KEYSTORE_BASE64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}
      - name: Releasing using Hub
        uses: alexrcq/action-release-apk@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_FOLDER: app